# runoak query provides several prefixes provided for free (by default)
PREFIX ENVO: <http://purl.obolibrary.org/obo/ENVO_>
SELECT distinct *
WHERE {
    ?biome rdfs:subClassOf+ ENVO:00000428 .
    minus {
        ?biome rdfs:subClassOf+ ENVO:00002030 .
    }
    filter(strstarts(str(?biome), "http://purl.obolibrary.org/obo/ENVO_")) # foodon asserts that some climate zones are biomes!
}
order by ?biome
limit 999
# runoak query gives labels for free by default

